# Generated by Django 5.0.6 on 2024-09-18 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0002_user_department_user_is_manager_user_pin_user_team"),
    ]

    operations = [
        migrations.RemoveField(model_name="user", name="department",),
        migrations.RemoveField(model_name="user", name="is_manager",),
        migrations.RemoveField(model_name="user", name="pin",),
        migrations.RemoveField(model_name="user", name="team",),
    ]
