# Generated by Django 5.0.6 on 2024-09-09 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_projectnote'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='assigned_team',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
