# Generated by Django 5.0.6 on 2024-09-09 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_project_assigned_team'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='assigned_team',
        ),
    ]
